### ISSUE TITLE
sls deploy not working for serverless

### ISSUE THREAD

**Issue by ahkai86** [MeRahulAhire/S3-Ultimate-Guide#1]
Hi Rahul Ahire! Great videos u have created for learners getting into servereless! I am one of those new bird learning serverless now after watching your videos =) Just had an issues running sls deploy and nothing happened in console after i input a new S3 bucket name. I am running the following versions:
VS code 1.55.2
npm 7.11.1
Framework Core: 2.38.0 (standalone)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0

**Comment by MeRahulAhire** [comment]
Could you please give some details of error logs or something more over it?

**Comment by ahkai86** [comment]
hi Rahul! Thanks for the prompt reply! i am still watching your video, but executing the command on my VS code terminal sls deploy doesnt trigger anything:

S3-Ultimate-Guide-master % sls deploy
S3-Ultimate-Guide-master %  

it just went blank, i have installed CLI, npm and nodejs as well previously

**Comment by MeRahulAhire** [comment]
@ahkai86 Have you configured the credentials?

**Comment by ahkai86** [comment]
hi yes , configured. I am able to run the the individual js script eg. node objects/getobject-presignedUrl.js     
but coming to the serverless.yml file i cannot execute serverless deploy or sls deploy

**Comment by ahkai86** [comment]
do you have the handler.js file for me to reference?

**Comment by MeRahulAhire** [comment]
What's your issue, I Still didn't got it. I don't have the basic `handler.js` file

**Comment by ahkai86** [comment]
Hi, basically i clone the repo and run it off VS code with the installed npm and nodejs modules prior to running sls deploy and its not running, when i create a new serverless project it was running ok with CF running in my AWS account, so i am still troubleshooting this issues to invoke your scripts in serverless.yml

**Comment by MeRahulAhire** [comment]
what's the problem? Let me know how can I help you precisely.

**Comment by ahkai86** [comment]
Hi Rahul, let me try out possible solutions again, i am running on mac big sur and some context is different from your settings, cheers!

**Comment by ahkai86** [comment]
Hi Rahul, i have finally got it deployed. Somehow i cant input the following 2 lines in serverless.yml. After removing it i can deploy the serverless command using sls deploy.

plugins:
  - serverless-ignore

**Comment by MeRahulAhire** [comment]
serverless-ignore is a plugin which you need to install via npm if you want to use it. If not you don't need it then let it be commented.
