### ISSUE TITLE
syntax error on index.html

### ISSUE THREAD

**Issue by ahkai86** [MeRahulAhire/S3-Ultimate-Guide#3]
Hi Rahul, for your frontend/index.html, found a syntax error

On line 43: 
should be  `<script src="./frontendPreSignedUrl.js"></script>` instead of 
` # <script src="./frontendPreSignedURL.js"></script>`

**Comment by MeRahulAhire** [comment]
Oh thanks for your observation. I fixed it. It seems you're learning S3 in full swing..
